### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by HarborYuan** [nianticlabs/panoptic-forecasting#1]
Hi, 

Thanks for your work.
We are trying to follow your work but we cannot download the data, although we successfully download the models.

The following two commands cannot be executed:
"""
gsutil -m cp gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/fg/* data/fg/
gsutil -m cp -r gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/bg/* data/bg/
"""
Error msg : zsh: no matches found: gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/bg/*

**Comment by cgraber** [comment]
Hi, thanks for your interest in our work!

It seems like this could be related to [this issue](https://github.com/GoogleCloudPlatform/gsutil/issues/499). Could you try putting the urls in quotes?

```
gsutil -m cp 'gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/fg/*' data/fg/
gsutil -m cp -r 'gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/bg/*' data/bg/
```
If this fixes the issue, I'll update the scripts to contain these quotes.

**Comment by HarborYuan** [comment]
Thanks for your response!

Sorry for the trivial question. It seems that the quotes are useful to make the zsh recognizing the link so that updating the scripts are useful. However, new exception is raised.

> ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.

I think maybe you need to grant the list permission of the folder or list the files in the script.

**Comment by lxtGH** [comment]
@cgraber Hi! Could you upload your data and model in google drive for us to download since I have no sudo in my lab server ?
Thanks!

**Comment by cgraber** [comment]
@HarborYuan good catch - I've taken another route and uploaded the data as compressed archives. Try the following:
```
mkdir -p data/
gsutil -m cp gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/fg.tar.gz data/
tar -xzvf data/fg.tar.gz -C data/
gsutil -m cp gs://niantic-lon-static/research/panoptic-forecasting/preprocessed-data/bg.tar.gz data/
tar -xzvf data/bg.tar.gz -C data/
```
(I'm pretty sure the permissions should be okay to download these files, but let me know if I got this wrong and I'll address it.)

@lxtGH you should be able to install the google cloud sdk locally, which will not require sudo access.

**Comment by HarborYuan** [comment]
@cgraber It works. I have downloaded the data.

Thanks.

**Comment by cgraber** [comment]
Excellent, I'm glad that fixed the problem. I have updated the download script so that others will not encounter the same issue.
