### ISSUE TITLE
Fail to download dataset using the download_data.sh script

### ISSUE THREAD

**Issue by szl0144** [nianticlabs/panoptic-forecasting#2]
Hi,

I install the Google Cloud SDK in my virtual machine and run the dataset download script. When I cp the cloud data into my local data folder I faced an error

_**AccessDeniedException: 403 XXX does not have storage.objects.list access to the Google Cloud Storage bucket.
CommandException: 1 file/object could not be transferred.**_

I am not familiar with the Google Cloud service, can you please tell me how to solve it? Thanks!

Best,
Shaoyi

**Comment by szl0144** [comment]
The answer in Q1 https://github.com/nianticlabs/panoptic-forecasting/issues/1#issuecomment-906819461 solves the problem. Thanks!

**Comment by cgraber** [comment]
Hi, I'm glad you were able to find the fix! I've updated the download script so that more people won't run into this issue as well.
